//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaRhoPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class committee_member
    {
        public int committee_member_id { get; set; }
        public int member_id { get; set; }
        public int committee_name_id { get; set; }
        public string semester { get; set; }
    
        public virtual committee_names committee_names { get; set; }
        public virtual member member { get; set; }
    }
}
