//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaRhoPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeltaRhoDBEntities : DbContext
    {
        public DeltaRhoDBEntities()
            : base("name=DeltaRhoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<brother> brothers { get; set; }
        public virtual DbSet<committee_names> committee_names { get; set; }
        public virtual DbSet<executive_board> executive_board { get; set; }
        public virtual DbSet<executive_council> executive_council { get; set; }
        public virtual DbSet<leader> leaders { get; set; }
        public virtual DbSet<officer_title> officer_title { get; set; }
        public virtual DbSet<planned_event> planned_event { get; set; }
        public virtual DbSet<point> points { get; set; }
        public virtual DbSet<point_requirement> point_requirement { get; set; }
        public virtual DbSet<point_type> point_type { get; set; }
        public virtual DbSet<point_type_grouping> point_type_grouping { get; set; }
        public virtual DbSet<point_type_permission> point_type_permission { get; set; }
        public virtual DbSet<status> status { get; set; }
    }
}
