//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaRhoPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class executive_council
    {
        public int committee_id { get; set; }
        public Nullable<int> position_id { get; set; }
        public Nullable<int> committee_name_id { get; set; }
        public Nullable<int> commitee_head { get; set; }
    
        public virtual brother brother { get; set; }
        public virtual committee_names committee_names { get; set; }
        public virtual leader leader { get; set; }
    }
}
