//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaRhoPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class executive_board
    {
        public int officer_id { get; set; }
        public Nullable<int> position_id { get; set; }
        public Nullable<int> officer_title_id { get; set; }
    
        public virtual officer_title officer_title { get; set; }
        public virtual leader leader { get; set; }
    }
}
