//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaRhoPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public member()
        {
            this.committee_member = new HashSet<committee_member>();
            this.initiation_application = new HashSet<initiation_application>();
            this.leaders = new HashSet<leader>();
            this.points = new HashSet<point>();
        }
    
        public int member_id { get; set; }
        public string student_pdid { get; set; }
        public Nullable<int> status_id { get; set; }
        public string brother_bio { get; set; }
        public byte[] headshot { get; set; }
        public string full_name { get; set; }
        public string preferred_pronouns { get; set; }
        public Nullable<System.DateTime> expected_graduation { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string major_minor { get; set; }
        public string nickname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<committee_member> committee_member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<initiation_application> initiation_application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<leader> leaders { get; set; }
        public virtual status status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<point> points { get; set; }
    }
}
